### ISSUE TITLE
2-sphere manifold in example 6

### ISSUE THREAD

**Issue by narutojxl** [hku-mars/IKFoM#1]
Hi, author,
Thanks for your hard-core paper and sharing to community very much!  I have three questions and want to ask for your help.  Could you recommend some reference materials about 2-sphere manifold?  Thanks for your help and time!
![image](https://user-images.githubusercontent.com/6205343/112135644-f69c5680-8c08-11eb-8fc8-2cf2bd8e094f.png)

**Comment by Joanna-HE** [comment]
1. From the fact that x denotes the gravity vector in body frame, the direction of it would change at the angular velocity of the body, which gives the equation (21).
2. For the state x that is in 2-sphere manifold, dot{x} is tangent to the 2-shpere space at point x. Taking equation (21) as example: 
<img width="214" alt="equa21 github issue" src="https://user-images.githubusercontent.com/55788638/112715696-d3c9b500-8f1c-11eb-866e-d3136655786d.png">
3. For this question, please refer to the "Vector triple product".

**Comment by Joanna-HE** [comment]
Hi, Thanks for your attention on our work!

1. From the fact that x denotes the gravity vector in body frame, the direction of it would change at the angular velocity of the body, which gives the equation (21).

2. For the state x that is in 2-sphere manifold, dot{x} is tangent to the 2-shpere space at point x. Taking equation (21) as example:
<img width="214" alt="equa21 github issue" src="https://user-images.githubusercontent.com/55788638/112716629-6ae53b80-8f22-11eb-93bc-519166f65660.png">

3. For this question, please refer to the "Vector triple product": 
<img width="237" alt="向量三重积" src="https://user-images.githubusercontent.com/55788638/112716632-6f115900-8f22-11eb-9682-1a4e81c30524.png">

**Comment by narutojxl** [comment]
Hi, author, 
Thanks for your detailed reply. I'm sorry i don't figure out how to use [Vector triple product](https://en.wikipedia.org/wiki/Triple_product#Vector_triple_product) to derive equ(23), this is my derivation. If we follow "Vector triple product", where should i change to get equ(23), thanks for your help!
![image](https://user-images.githubusercontent.com/6205343/112782051-b4e33400-907e-11eb-825a-a7791340fc1c.png).

**Comment by Joanna-HE** [comment]
![github_issue](https://user-images.githubusercontent.com/55788638/113252755-cdf61a00-92f6-11eb-8307-6ed701e33a65.jpg)

**Comment by narutojxl** [comment]
Hi author,
Thanks for your help. Please forgive me stupid question, how we get the following equation from  "Vector triple product", which is about three vectors cross product, but here we only have two vectors. Again, thanks!
![image](https://user-images.githubusercontent.com/6205343/113287770-9b611700-9320-11eb-8174-5948bfd85da9.png)

**Comment by Joanna-HE** [comment]
Hi, please take the "x" at the end of the right side of equation as the third vector, it will appear as a standard vector triple product.

**Comment by narutojxl** [comment]
Thanks author's kind and patient instruction, my problem is solved.
