### ISSUE TITLE
Yaw角观测函数如何写

### ISSUE THREAD

**Issue by ZhongKang97** [hku-mars/IKFoM#11]
作者您好，我现在对载体有一个yaw角的观测量，请问如何写对应的h和h_x呢，有对应的示例吗，感激不尽！

**Comment by Joanna-HE** [comment]
把yaw角的观测转换成一个方向向量，比如指南针，在这个例子里R^T*e3就是测量了。

**Comment by ZhongKang97** [comment]
好的，感谢您的回复，我试试看

**Comment by ZhongKang97** [comment]
> 把yaw角的观测转换成一个方向向量，比如指南针，在这个例子里R^T*e3就是测量了。

好的，感谢您的回复，我试试看

**Comment by ZhongKang97** [comment]
> 把yaw角的观测转换成一个方向向量，比如指南针，在这个例子里R^T*e3就是测量了。

![image](https://user-images.githubusercontent.com/47888587/205609261-8b799cfa-2f3b-44db-b3cc-2fb0360ca8db.png)
您看我这样写可以吗
