### ISSUE TITLE
Question about the observation model

### ISSUE THREAD

**Issue by unageek** [hku-mars/IKFoM#14]
Could you help me understand the error-state Kalman filter on [your paper](https://arxiv.org/abs/2102.03804)? According to (33), the observation model (the likelihood) is defined as $p(𝐃_{k+1}^j 𝐯_{k+1} \mid δ𝐱_j)$. Why the left-hand side of the bar is not $𝐳_{k+1}$ but $𝐃_{k+1}^j 𝐯_{k+1}$?

**Comment by Joanna-HE** [comment]
Yes, D_{k+1}^j v_{k+1} is the linearized noise of z_{k+1}.

**Comment by unageek** [comment]
Hmm... let me ask from a different perspective. The MAP estimation reduces to (37):

```math
δ𝐱_j^o = \arg\min_{δ𝐱_j} ‖𝐫_{k+1}^j - 𝐇_{k+1}^j δ𝐱_j‖_{\bar{\mathcal R}_{k+1}}^2 + \text{(the prior term)}.
```

Intuitively, we want to find the optimal $δ𝐱_j$ that minimizes the magnitude of the residual $𝐫_{k+1}^j$. So should not the first term just be $‖𝐫_{k+1}^j‖ _{\\bar{\\mathcal R} _{k+1}}^2$? Apparently, I am missing some point.

**Comment by Joanna-HE** [comment]
We want to find the optimal \delta x_j to minimize the magnitude of residual r_{k+1}, therefore, \delta x_j should appear in the MAP formulation, and the relationship of \delta x with the residual r_{k+1} should also be determined. The equation ||r_{k+1}||^2 with only r_{k+1} is meaningless.

**Comment by unageek** [comment]
OK, but then, the posterior distribution is $p(δ𝐱_j ∣ 𝐃_{k+1}^j 𝐯_{k+1})$ by Bayes' theorem, right? It does not make sense to me, since it does not contain the actual measurement $𝐳_{k+1}$.

**Comment by unageek** [comment]
I have obtained (37) by maximizing the posterior probability

```math
p(𝐱_{k+1}∣𝐳_{k+1},…) = p(𝐳_{k+1}∣𝐱_{k+1},…) p(𝐱_{k+1}∣…)
```

with respect to $𝐱_{k+1}$. Let me close this issue. Thank you for your assistance!
