### ISSUE TITLE
How to simplify the solution of equation Eq.(38) in the paper？

### ISSUE THREAD

**Issue by zhoupengwei** [hku-mars/IKFoM#3]
Hi author, Thank you for your work. I can't get the form in your article in the process of simplifying the solution of \delta j in Eq.(38).
I showed my calculation process and hope to get your help. I hope you can understand my problem. 
![微信图片_20210818220557](https://user-images.githubusercontent.com/55874402/129913964-ae49c244-060d-4a22-8628-a948cc59735f.jpg)

**Comment by Joanna-HE** [comment]
Firstly verify the equation in
<img width="268" alt="1632104825(1)" src="https://user-images.githubusercontent.com/55788638/133988303-e050fdf1-ff4c-4b3a-8eaf-a2bda062b314.png">.

Then substitute this equation into the equation shown in the bottom of your picture, the equal will be obtained.

**Comment by Joanna-HE** [comment]
Sorry for the late reply.

**Comment by zhoupengwei** [comment]
@Joanna-HE Thank you for your reply, my problem has been solved.

**Comment by qpc001** [comment]
> @Joanna-HE谢谢你的回复，我的问题已经解决了。

 请问你是怎么解决的?
