### ISSUE TITLE
常量维度测量值更新函数定义问题

### ISSUE THREAD

**Issue by shuqiu0202** [hku-mars/IKFoM#8]
作者您好，想请教一个问题：
Readme里面看到当测量值是常量维度时的第5步，需要实现一个输出等式"Implement the output equation h(x,v)"，并求相关的偏导
假如我现在需要在原有的激光雷达的测量更新基础上，再利用rtk提供的位置信息，对fast-lio的状态向量中位置P进行测量更新，我定义如下的函数是否可行？期待您的回复
![image](https://user-images.githubusercontent.com/29755583/167392084-41140dc1-976f-414f-81aa-1626d3fac7a6.png)

**Comment by Joanna-HE** [comment]
Sorry for the late reply, the functions look ok.

Best regards,

**Comment by shuqiu0202** [comment]
ok，thanks very much!

**Comment by Joanna-HE** [comment]
Maybe it is too late... I would like to inform that the variable 'valid' is used to stop the iterated EKF update by the user-defined conditions, other than the convergence condition and the max_num iteration condition.

Best regards,

Dongjiao HE

**Comment by shuqiu0202** [comment]
> Maybe it is too late... I would like to inform that the variable 'valid' is used to stop the iterated EKF update by the user-defined conditions, other than the convergence condition and the max_num iteration condition.
> 
> Best regards,
> 
> Dongjiao HE

非常感谢您的提醒，之前测试了此种将rtk位置作为独立测量的方式进行数据融合，觉得效果不是很好，也有可能是我哪里没弄对，后来用的方法是在fast_lio2的测量更新的H矩阵上加了几行来观测rtk的位置，建图效果好了很多。

**Comment by Joanna-HE** [comment]
如果rtk和lidar的测量不在同一个时刻的话，需要分别进行更新，比如lidar测量是t1时刻到来，rtk是在t2时刻到来，那么在t1时刻进行完lidar的更新后，需要进行一次predict，将状态predict到t2时刻，再进行rtk的更新

**Comment by AttiTudee** [comment]
> > Maybe it is too late... I would like to inform that the variable 'valid' is used to stop the iterated EKF update by the user-defined conditions, other than the convergence condition and the max_num iteration condition.
> > Best regards,
> > Dongjiao HE
> 
> 非常感谢您的提醒，之前测试了此种将rtk位置作为独立测量的方式进行数据融合，觉得效果不是很好，也有可能是我哪里没弄对，后来用的方法是在fast_lio2的测量更新的H矩阵上加了几行来观测rtk的位置，建图效果好了很多。

您好，最近也在尝试这部分工作，但没有啥进展，能否告知下是如何添加H矩阵的呢，十分感谢
